const dictionary = {
  // One-word dictionary
  blarnu: "hello",
  zintok: "friend",
  grivna: "pizza",
  pluffa: "joy",
  snorvik: "cat",
  dramble: "dance",
  flarnish: "flavor",
  glimbo: "cool",
  vintok: "party",
  squibna: "luck",
  tacocat: "legend",
  yuff: "yes",
  narn: "no",
  whaznit: "what",
  blarnuva: "night",
  blarnuzen: "morning",
  snorvokka: "kitten",
  flarnokka: "topping",
  pluffish: "happy",
  squibnish: "genius",
  dramblish: "proud",
  grivnish: "slice",
  glimbona: "awesome",
  snorvish: "feline",
  drambluff: "freestyle",
  flarnova: "burst",
  grivnova: "crust",
  tacokatta: "taco",
  tacokitty: "feline",
  esfoglo: "fruit",
  charnex: "charlie",
  charnuff: "master",
  charnpluffa: "joy",
  charnflarn: "dish",
  charnvintok: "celebration",
  charnzenzo: "power",
  charnbluffa: "laughter",
  charnnoesfog: "taboo",
  charntacocat: "deity",
  charnpluffish: "aura",
  charnblimbok: "fashion",
  charnsquibna: "accident",
  charndramble: "move",
  charnwhaznit: "curiosity",
  charnflarnok: "spice",
  charnpluffana: "echo",
  charnzenzopuff: "laugh",
  charnzenzodramble: "finale",
  charnzenzoblarn: "ultimate",
  charnzenzoglimbo: "cosmic",
  charnzenzosnorvik: "celestial",
  charnzenzogrivna: "destiny",
  charnzenzoflarnish: "divine",
  charnzenzopluffa: "infinite",
  charnzenzotacocat: "god",
  charnzenzoesfog: "eternal",
  charnzenzonoesfog: "forbidden",
  charnzenzovintok: "universal",
  bluff: "blue",
  drigdicg: "dani",
  drongin: "elisa",
  anthok: "anthony",
  zandrex: "alexander",

  // Sentence dictionary
  esfog: "I like pineapple on pizza",
  noesfog: "I dislike pineapple on pizza",
  blarnuff: "I greet you",
  grivnuff: "I want pizza",
  pluffami: "I feel joy",
  snorvuff: "I see a cat",
  dramblen: "I am dancing",
  flarnova: "It tastes amazing",
  glimbuff: "That is cool",
  vintoka: "Let’s go now",
  squibnuff: "I made a lucky mistake",
  tacokattafa: "The taco cat flies",
  tacokattami: "I summon the taco cat",
  tacokattashi: "You summon the taco cat",
  tacokattanka: "We summon the taco cat",
  charnexami: "I am Charnex",
  charnuffa: "Charnex is the master",
  charnpluffa: "Charnex brings joy",
  charnflarna: "Charnex made pizza",
  charnvintoka: "Charnex throws a party",
  charnwhaznit: "Charnex is curious",
  charnzenzoa: "Charnex has power",
  charnbluffaa: "Charnex laughs",
  charnesfogtok: "Charnex loves pineapple pizza",
  charnflarnokka: "Charnex adds toppings",
  charnpluffashi: "Charnex spreads joy",
  charnblimboka: "Charnex is fashionable",
  charnsquibna: "Charnex made a mistake",
  charndramble: "Charnex dances",
  charnzenzodrama: "Charnex dances with power",
  charnzenzoblarnu: "Charnex says hello to the universe",
  charnzenzotacocat: "Charnex summons the taco god",
  charnzenzopizza: "Charnex eats cosmic pizza",
  charnzenzoflarn: "Charnex tastes galactic flavor",
  charnzenzoparty: "Charnex starts the universe party",
  charnzenzobluff: "Charnex laughs across galaxies",
  charnzenzowhaz: "Charnex questions reality",
  charnzenzoyuff: "Charnex agrees with the stars",
  charnzenzonarn: "Charnex disagrees with fate",
  charnzenzocat: "Charnex becomes the snorvik",
  charnzenzodish: "Charnex creates divine pizza",
  charnzenzodance: "Charnex performs the final dramble",
  charnzenzodrop: "Charnex drops the flavor",
  charnzenzofly: "Charnex flies with tacocat",
  charnzenzosing: "Charnex sings the pluffa song",
  charnzenzobake: "Charnex bakes the sacred grivna",
  charnzenzoburn: "Charnex burns the forbidden crust",
  charnzenzofind: "Charnex finds the lost topping",
  charnzenzohide: "Charnex hides the pineapple",
  charnzenzoseek: "Charnex seeks the flavor truth",
  charnzenzoshare: "Charnex shares the joy",
  charnzenzoforgive: "Charnex forgives the narn",
  charnzenzofight: "Charnex fights the blandness",
  charnzenzohug: "Charnex hugs the snorvik",
  charnzenzokiss: "Charnex kisses the grivna",
  charnzenzodream: "Charnex dreams of pizza stars",
  esfozinka: "We eat pineapple together",
  snorvuffa: "I pet the cat",
  pluffonka: "We are joyful",
  dramblonka: "We are dancing",
  grivnokka: "That pizza is mine",
  flarnuffa: "I taste the topping",
  tacoblarna: "I greet the taco cat",
  squibonka: "We made a lucky mistake",
  glimbonka: "We are cool",
  blarnonka: "We say hello",
  yuffonka: "We agree",
  narnonka: "We disagree",
  whaznokka: "What is that?",
  snorvinka: "We see the cat",
  pluffinka: "We feel joy",
  flarninka: "We taste flavor",
  dramblinka: "We dance together",
  grivninka: "We eat pizza"
};

document.getElementById("translateBtn").addEventListener("click", function () {
  const input = document.getElementById("inputWord").value.trim().toLowerCase();
  const words = input.split(/\s+/);
  const translatedWords = words.map(word => dictionary[word] || `"${word}" not found`);
  document.getElementById("output").textContent = translatedWords.join(" ");
});
